### ISSUE TITLE
Tests failing on Cygwin

### ISSUE THREAD

**Issue by trungnt2910** [jart/blink#26] opened 2023-01-14 05:35 UTC
Running `make check` on Windows Server 2022 x64 and Cygwin fails.

```
I2023-01-14T05:32:35.243212:blink/blink.c:81:262144 SEGMENTATION FAULT (Segmentation fault) AT ADDRESS fffff778010b9f40
	 PC 42e7d0 test %rax,%rax
	 AX 0000000000000000  CX 0000100080090538  DX 0000100080090010  BX 00001000800904d0
	 SP 00001000800afff0  BP 000070000000fde0  SI 00001000800afff0  DI 0000000001390f00
	 R8 0000100080090500  R9 000000000040d090 R10 0000100080090538 R11 0000000000000000
	R12 000000000040d090 R13 000000000000fff0 R14 0000100080090010 R15 00001000800a0000
	 FS 0000100080090500  GS 0000000000000000 OPS 11787            JIT 0               
	third_party/cosmo/2/memory_test.com
	70000000fde0 00000042e7d0 sys_clone_linux+0x13
	70000000fea0 000000418f23 clone+0x1e3 192 bytes
	70000000ff00 00000040d169 _spawn+0x99 96 bytes
	70000000ff40 00000040cdaf memory_test+0x5f 64 bytes
	70000000ff80 00000042d0aa __gc 64 bytes
	70000000ff90 00000040ccb1 testlib_runalltests+0x61 16 bytes
	70000000ffe0 000000402bc2 main+0x192 80 bytes
	4fffffffcc90 0000004030ad cosmo+0x4d [STRAY]
	000000000000 0000004025c4 _start+0x82
I2023-01-14T05:32:35.243753:blink/syscall.c:270:262144 halting machine from thread: -4
make: *** [third_party/cosmo/cosmo.mk:20: o//third_party/cosmo/2/memory_test.com.ok] Error 252
make: *** Waiting for unfinished jobs....
```

For the full log, see [here](https://github.com/trungnt2910/blink/actions/runs/3917084763/jobs/6696649666).

**Comment by trungnt2910** [comment] 2023-01-15 17:44
After messing things up on a [fork](https://github.com/trungnt2910/blink/actions/runs/3924544734/jobs/6708869952), the failing line seems to be here:

```c
  err = pthread_create(&m2->thread, &attr, OnSpawn, m2);
```

**Comment by jart** [comment] 2023-01-15 20:42
Marking as duplicate of #27 which is being worked on now.

**Closed by jart** 2023-01-15 20:42 UTC

**Comment by trungnt2910** [comment] 2023-01-16 02:42
After using a combination of Visual Studio debugger and `addr2line`, I found out that the function that causes the segfault is:

```
nexgen32e_f GetHook(struct Machine *m, u64 pc) {
  int off = atomic_load_explicit(m->fun + (uintptr_t)pc, memory_order_relaxed);
  return off ? (nexgen32e_f)(IMAGE_END + off) : GeneralDispatch;
```
